### ISSUE TITLE
Problem with Tomcat server.

### ISSUE THREAD

**Issue by Sadowskyy** [vladimir-bukhtoyarov/bucket4j#127]
Hi when I implemented your libary into my project console output dozens of exceptions.

   example 
       |
     

- [ ]  \/

https://pastebin.com/HVNQEDv8

**Comment by vladimir-bukhtoyarov** [comment]
Hello @Sadowskyy,

Stacktrace is clear:
```
...
Caused by: org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/C:/Users/Wiktor%20Sadowski/IdeaProjects/portfolioWS/target/classes/ehcache.xml
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:124) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:90) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.jsr107.EhcacheCachingProvider$ConfigSupplier.getConfiguration(EhcacheCachingProvider.java:328) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	... 85 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-elt.1.a: Cannot find the declaration of element 'config'.
...
```

You need to correct ```ehcache.xml``` file according to Ehcache rules, see examples [there](https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples/tree/master/bucket4j-spring-boot-starter-example-ehcache)

**Comment by Sadowskyy** [comment]
Thanks for help :3
