### ISSUE TITLE
ClassNotFoundException : Issue with Hazelcast sidecar implementation with bucket4j in Kubernetes cluster w

### ISSUE THREAD

**Issue by akshay-dawankar** [vladimir-bukhtoyarov/bucket4j#134]
```
Caused by: java.lang.NoClassDefFoundError: io/github/bucket4j/grid/hazelcast/Hazelcast
	at com.common.service.RateLimiterService.init(RateLimiterService.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 157 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.github.bucket4j.grid.hazelcast.Hazelcast
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 165 common frames omitted
```

Facing the above issue while implementation bucket4j with Hazelcast sidecar implementation in Kubernetes cluster

```
import java.time.Duration;
import java.util.function.Supplier;

import javax.annotation.PostConstruct;

import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Service;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;

import io.github.bucket4j.Bandwidth;
import io.github.bucket4j.Bucket;
import io.github.bucket4j.Bucket4j;
import io.github.bucket4j.BucketConfiguration;
import io.github.bucket4j.Refill;
import io.github.bucket4j.grid.ProxyManager;


@Service
@Slf4j
public class RateLimiterService {

	ProxyManager<String> buckets;

	@PostConstruct
	void init() {
		Config config=new Config();
		HazelcastInstance hazelcastInstance=Hazelcast.newHazelcastInstance(config);
		buckets = Bucket4j.extension(io.github.bucket4j.grid.hazelcast.Hazelcast.class).proxyManagerForMap(hazelcastInstance.getMap("buckets"));
	}
	
	
	public synchronized boolean verifyLimit() {
		
			try {
		
				return buckets.getProxy("allAPIBucket", getBucketConfig()).asScheduler().tryConsume(1,Duration.ofSeconds(2));
			}catch (Exception e) {
				log.error("Error while trying to consume {}", e.getStackTrace());
				
			}
	
	
	}

	private Supplier<BucketConfiguration> getBucketConfig() {
		return () -> Bucket4j.configurationBuilder()
				.addLimit(Bandwidth.classic(10, Refill.intervally(10, Duration.ofSeconds(1)))).build();
	}
}
```

dependencies :
```
	<dependency>
		    <groupId>com.github.vladimir-bukhtoyarov</groupId>
		    <artifactId>bucket4j-hazelcast</artifactId>
		    <version>4.10.0</version>
		    <scope>provided</scope>
		</dependency>
        <dependency>
    		<groupId>com.github.vladimir-bukhtoyarov</groupId>
   			<artifactId>bucket4j-jcache</artifactId>
    		<version>4.10.0</version>
		</dependency>
		 <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
	      	<groupId>com.hazelcast</groupId>
	      	<artifactId>hazelcast-all</artifactId>
	      	<version>4.0</version>
    	</dependency>
    	<dependency>
		    <groupId>com.github.vladimir-bukhtoyarov</groupId>
		    <artifactId>bucket4j-core</artifactId>
		    <version>4.10.0</version>
		</dependency>
```

**Comment by vladimir-bukhtoyarov** [comment]
@akshay-dawankar hello,

Please read this https://github.com/vladimir-bukhtoyarov/bucket4j/issues/66#issuecomment-372991892

**Comment by akshay-dawankar** [comment]
Thank you for the reply @vladimir-bukhtoyarov.

I have already tried this  #66 and checked the docker image mentioned in that. But still failing with the same issue. Dependencies mentioned are already added bucket4j-hazelcast,bucket4j-jcache and bucket4j-core. also hazelcast-all is present.

**Comment by vladimir-bukhtoyarov** [comment]
@akshay-dawankar remote debug should help you. It is obvious that problems are related to the classpath, so just debug your classloader.
