### ISSUE TITLE
Coherence 12.2.1.4.7 with Bucket4j 6.2.0 fails with java.io.IOException: Unknown type id 768

### ISSUE THREAD

**Issue by nikhilvaishnavi** [vladimir-bukhtoyarov/bucket4j#176]
We recently upgraded to bucket4j 6.2.0 from previous 4.10.0 and started noticing the below error whenever we execute this code -
`// init bucket registry
 NamedCache<String, GridBucketState> cache = CacheFactory.getCache("RateLimit");

  //Proxy manager / weak pointer to buckets.
  ProxyManager<String> buckets = Bucket4j.extension(Coherence.class).proxyManagerForCache(cache);
  Optional<BucketConfiguration> existingConfigurationOptional = buckets.getProxyConfiguration(requestKey);`

We have added all the required serializers as listed in the documentation here - https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/coherence.md

Error stack trace -

`java.lang.RuntimeException: java.io.IOException: Unknown type id 768
	at com.tangosol.util.ExternalizableHelper.fromBinary(ExternalizableHelper.java:416)
	at com.tangosol.util.ExternalizableHelper.fromBinary(ExternalizableHelper.java:349)
	at com.tangosol.coherence.component.net.extend.RemoteNamedCache$ConverterFromBinary.convert(RemoteNamedCache.CDB:4)
	at com.oracle.common.collections.ConverterCollections$ConverterMap.get(ConverterCollections.java:1558)
	at com.tangosol.coherence.component.net.extend.RemoteNamedCache.get(RemoteNamedCache.CDB:1)
	at com.tangosol.coherence.component.util.SafeNamedCache.get(SafeNamedCache.CDB:1)
	at io.github.bucket4j.grid.coherence.CoherenceProxy.getConfiguration(CoherenceProxy.java:81)
	at io.github.bucket4j.grid.coherence.CoherenceProxyManager.getProxyConfiguration(CoherenceProxyManager.java:64)
	at 
Caused by: java.io.IOException: Unknown type id 768
	at com.tangosol.io.pof.ConfigurablePofContext.deserialize(ConfigurablePofContext.java:385)
	at com.tangosol.io.Serializer.deserialize(Serializer.java:89)
	at com.tangosol.util.ExternalizableHelper.deserializeInternal(ExternalizableHelper.java:3204)
	at com.tangosol.util.ExternalizableHelper.fromBinary(ExternalizableHelper.java:412)
	... 27 more
Caused by: java.lang.IllegalStateException: Unknown type id 768
	at io.github.bucket4j.serialization.DataStreamAdapter.readObject(DataStreamAdapter.java:118)
	at io.github.bucket4j.serialization.DataStreamAdapter.readObject(DataStreamAdapter.java:109)
	at io.github.bucket4j.serialization.DataStreamAdapter.readObject(DataStreamAdapter.java:49)
	at io.github.bucket4j.grid.GridBucketState$1.deserialize(GridBucketState.java:44)
	at io.github.bucket4j.grid.GridBucketState$1.deserialize(GridBucketState.java:40)
	at io.github.bucket4j.grid.coherence.pof.AbstractBucket4jPofSerializer.deserialize(AbstractBucket4jPofSerializer.java:76)
	at com.tangosol.io.pof.PofBufferReader.readAsObject(PofBufferReader.java:3619)
	at com.tangosol.io.pof.PofBufferReader.readObject(PofBufferReader.java:2890)
	at com.tangosol.io.pof.ConfigurablePofContext.deserialize(ConfigurablePofContext.java:379)
	... 30 more`

**Comment by vladimir-bukhtoyarov** [comment]
Hello @nikhilvaishnavi

![image](https://user-images.githubusercontent.com/6761830/134762401-c42c8843-1a9c-4296-a9e1-612dc6dea3ce.png)

The part of stacktrace above tells that problem is related to internal Coherence types not Bucket4j types, because clients are not allowed to specify type numbers less than 1000. So looks that you need the consultation with the Oracle team, or getting help on some Coherence related forums.

**Comment by nikhilvaishnavi** [comment]
@vladimir-bukhtoyarov But the root cause in stack trace seem to originate from Bucket4j where we are trying to deserialize an object which for which no deserializer is defined - 

Look at the last trace - Am I reading it wrong ? I did see in the coherence jar there is not type id 768 defined as well but maybe we are requesting for deserializing an object which is not defined in coherence.
Caused by: java.lang.IllegalStateException: Unknown type id 768
	at io.github.bucket4j.serialization.DataStreamAdapter.readObject(DataStreamAdapter.java:118)
	at io.github.bucket4j.serialization.DataStreamAdapter.readObject(DataStreamAdapter.java:109)
	at io.github.bucket4j.serialization.DataStreamAdapter.readObject(DataStreamAdapter.java:49)
	at io.github.bucket4j.grid.GridBucketState$1.deserialize(GridBucketState.java:44)
	at io.github.bucket4j.grid.GridBucketState$1.deserialize(GridBucketState.java:40)
	at io.github.bucket4j.grid.coherence.pof.AbstractBucket4jPofSerializer.deserialize(AbstractBucket4jPofSerializer.java:76)

**Comment by vladimir-bukhtoyarov** [comment]
Yes. You are right. What version of Coherence do you use?

**Comment by vladimir-bukhtoyarov** [comment]
@nikhilvaishnavi I need for 12.2.1.4.7 Coherence distribution to do compatibility testing.

Also I have additional questions:
* Where you got this exception of production on production or inside staging environment or on developer's machine? If on production then what is the time to live of records in your cache? Is it real that cache entry had been written by legacy Bucket4j version and was read by a new Bucket4j version?
* Did you upgrade Coherence by itself or Bucket4j only?
* What happens if not using POF serializer? Does upgrade from 4.10.0 to 6.2.0 works without POF serialization feature?

**Comment by nikhilvaishnavi** [comment]
Attached the coherence jar - [coherence-12.2.1.4.7.jar.zip](https://github.com/vladimir-bukhtoyarov/bucket4j/files/7282861/coherence-12.2.1.4.7.jar.zip)

Answer to your questions inline - 

- Where you got this exception of production on production or inside staging environment or on developer's machine? If on production then what is the time to live of records in your cache? Is it real that cache entry had been written by legacy Bucket4j version and was read by a new Bucket4j version?
> I am able to see this in my local env (developer's machine). The TTL in prod/local machine is 90 min. All the entries in cache are for new Bucket4j version.

- Did you upgrade Coherence by itself or Bucket4j only? 
> Bucket4J only

- What happens if not using POF serializer? Does upgrade from 4.10.0 to 6.2.0 works without POF serialization feature?
> I am not clear about this - how do I turn of POF serializing. Note we already use coherence in our application with POF serialization and I was just plugging in bucket4j into our system due to this. If there is a way to do it for bucket4j I am open to try it out

**Comment by nikhilvaishnavi** [comment]
@vladimir-bukhtoyarov I think I may have found the root cause. We have the coherence cache cluster as a separate docker image. What I have come to understand is every time client changes, we need to rebuilt the coherence docker image to pick up any pof related changes as well.
We need to rebuild it with the new client version of bucket4j which resolves this issue. 
Thanks for looking into this
